#############################################################################
# Makefile for building: AboutWin
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  AboutWin.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile AboutWin.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -pthread -pthread -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0 -I../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0 -I../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/lib/glib-2.0/include -I../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/orc-0.4 -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AboutWin1.0.0
DISTDIR = /home/minji/Desktop/Qt\ files/Example/AboutWin/.tmp/AboutWin1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		aboutme.cpp qrc_resource2.cpp \
		qrc_resource_211116.cpp \
		moc_mainwindow.cpp \
		moc_aboutme.cpp
OBJECTS       = main.o \
		mainwindow.o \
		aboutme.o \
		qrc_resource2.o \
		qrc_resource_211116.o \
		moc_mainwindow.o \
		moc_aboutme.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		AboutWin.pro mainwindow.h \
		aboutme.h main.cpp \
		mainwindow.cpp \
		aboutme.cpp
QMAKE_TARGET  = AboutWin
DESTDIR       = 
TARGET        = AboutWin


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_aboutme.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: AboutWin.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		AboutWin.pro \
		resource2.qrc \
		resource_211116.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile AboutWin.pro -spec linux-g++
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/link_pkgconfig.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
AboutWin.pro:
resource2.qrc:
resource_211116.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile AboutWin.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resource2.qrc resource_211116.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h aboutme.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp aboutme.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui aboutme.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resource2.cpp qrc_resource_211116.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource2.cpp qrc_resource_211116.cpp
qrc_resource2.cpp: resource2.qrc \
		/usr/lib/qt5/bin/rcc
	/usr/lib/qt5/bin/rcc -name resource2 resource2.qrc -o qrc_resource2.cpp

qrc_resource_211116.cpp: resource_211116.qrc \
		/usr/lib/qt5/bin/rcc \
		img/testimage2.jpeg \
		img/testimage.jpg
	/usr/lib/qt5/bin/rcc -name resource_211116 resource_211116.qrc -o qrc_resource_211116.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -pthread -pthread -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_aboutme.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_aboutme.cpp
moc_mainwindow.cpp: aboutme.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/minji/Desktop/Qt files/Example/AboutWin' -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0 -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0 -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/lib/glib-2.0/include -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_aboutme.cpp: aboutme.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/minji/Desktop/Qt files/Example/AboutWin' -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0 -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0 -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/lib/glib-2.0/include -I/home/minji/4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/orc-0.4 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include aboutme.h -o moc_aboutme.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_aboutme.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_aboutme.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_aboutme.h: aboutme.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic aboutme.ui -o ui_aboutme.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		aboutme.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		aboutme.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

aboutme.o: aboutme.cpp aboutme.h \
		ui_aboutme.h \
		mainwindow.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/galloca.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtypes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/lib/glib-2.0/include/glibconfig.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmacros.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gversionmacros.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/garray.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gasyncqueue.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gthread.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gatomic.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gerror.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gquark.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gbacktrace.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gbase64.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gbitlock.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gbookmarkfile.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gbytes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gcharset.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gchecksum.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gconvert.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gdataset.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gdate.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gdatetime.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtimezone.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gdir.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/genviron.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gfileutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/ggettext.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/ghash.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/glist.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmem.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gnode.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/ghmac.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/ghook.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/ghostutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/giochannel.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmain.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gpoll.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gslist.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gstring.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gunicode.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gkeyfile.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmappedfile.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmarkup.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gmessages.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gvariant.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gvarianttype.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/goption.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gpattern.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gprimes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gqsort.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gqueue.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/grand.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/grcbox.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/grefcount.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/grefstring.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gregex.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gscanner.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gsequence.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gshell.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gslice.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gspawn.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gstrfuncs.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gstringchunk.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtestutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gthreadpool.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtimer.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtrashstack.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gtree.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gurifuncs.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/guuid.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gversion.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/gwin32.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/gallocator.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/gcache.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/gcompletion.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/gmain.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/grel.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/deprecated/gthread.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib/glib-autocleanups.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gst.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/glib-compat.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstenumtypes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/glib-object.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gbinding.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gobject.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gtype.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gvalue.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gparam.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gclosure.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gsignal.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gmarshal.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gboxed.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/glib-types.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/genums.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gparamspecs.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gsourceclosure.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gtypemodule.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gtypeplugin.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gvaluearray.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gvaluetypes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/glib-enumtypes.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/glib-2.0/gobject/gobject-autocleanups.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstconfig.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstversion.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstatomicqueue.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstbin.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstelement.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstobject.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcontrolbinding.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcontrolsource.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstclock.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpad.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstbuffer.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstminiobject.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstallocator.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstmemory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcaps.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gststructure.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdatetime.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcapsfeatures.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstmeta.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstbufferlist.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpadtemplate.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstevent.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstformat.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstiterator.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttaglist.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstsample.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstsegment.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstmessage.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstquery.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttoc.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcontext.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdevice.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gststreams.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gststreamcollection.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttask.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttaskpool.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstbus.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstelementfactory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstplugin.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstmacros.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpluginfeature.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsturi.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstbufferpool.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstchildproxy.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdebugutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdevicemonitor.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdeviceprovider.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdeviceproviderfactory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstdynamictypefactory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstelementmetadata.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsterror.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstghostpad.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstinfo.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstparamspecs.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstvalue.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpipeline.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpoll.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpreset.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstprotection.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstregistry.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstpromise.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstsystemclock.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttagsetter.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttocsetter.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttracer.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttracerfactory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttracerrecord.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttypefind.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gsttypefindfactory.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstutils.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstparse.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/gstcompat.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/video/videooverlay.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/video/gstvideosink.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/base/gstbasesink.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/base/base-prelude.h \
		../../../../4_ultra96_211113/Design-Project_211111/images/linux/sdk/sysroots/aarch64-xilinx-linux/usr/include/gstreamer-1.0/gst/video/video-prelude.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutme.o aboutme.cpp

qrc_resource2.o: qrc_resource2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource2.o qrc_resource2.cpp

qrc_resource_211116.o: qrc_resource_211116.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource_211116.o qrc_resource_211116.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_aboutme.o: moc_aboutme.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutme.o moc_aboutme.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/root || mkdir -p $(INSTALL_ROOT)/root
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/root/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/root/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/root/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/root/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

